language: java
jdk:
  - oraclejdk8
services:
  - docker

install: mvn install dockerfile:build

before_deploy: cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script:
  - mvn deploy
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push drivereu/driver-testbed-sec-authz-service

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  
env:
  global:
  - secure: qJ6eIJsvEh2dJOuQsnc0lZ9WzIT61Hqoia8VhDLpgHQAiQHbtcw7FioDUqjQ5578iUau49q2dzrPmPSnzjOX1drjXlbYCz7REbqkeHbvUvz7uSQsKckVHc5hmsjLGw1ntbwebi6hAmMkUt56dXuc2i7DXaCFBiIiRuOxH+RWlQc08tc0hW592lUp2yo01gJp4QOSFKRHNSE3mFf+Mo3z+Ph/roJ8EnhkI46r/2tqtBYBT+RFgZiQjWJbcrh93brCXCeoEJvhv/C6FXn1K2Tq7GS2YqU7MBlD2bjME/bERjuPMHNNrskgYMcGhG53xKtTHyVV38lAGKyVW7sFJmMhmfzrxb8XYs8hT1Vq4CUd3gh5oaD42afWOhqTgq9wRziI5NQEIamkF3rutG7J9eE3yOnJlZSj0Li3DNx/ThX9BeVKUkWjCd9BTQX02hY7hhD2iSXu/MTnLGCz07YLvnOX36dsE/wT6rUVSzw6TvQiwFkiQMNArhJt9oHrD5PTbILFksY+reIMO12mq8M+g9AWwRvUqGWMe8CuCMvbVix2pFdB0kaMvb7lTGCRXXhumQ0bZ8dOEVgCmQFgJQRlxX5Tw0xYCnIPcjZ0QAlTHIta0yqUqBuGR/hljFzQbEz4lMchV4NhIBnGSMr0VS0YZBc4F4DoC2ufkwtZN2qpQOKgtn0=
  - secure: jE+Yh1H/JUBrbYT4mmSfyvmEbkjFZv1vrNM0nWBDwK3nMtwaQ1oGi6O/av61Kowdx3cFpuujBKfglu7aJI35XZuDGQ40t9QWMFwnGoVoadjeMhpO09HyAc3jIbc1PqNQATucWVis9K8KV47Kq4AAoPpuUSf2SAmTgcR60Q2kkWrHQUntF9R3INTJFU2LmxtwF+ofDvejQIXTT/yQ9mBI1kVk5KLnwpNVmW3StaEmEhOSNBnfLgH0NZ15OONGOGQQt93FjRKZ/sHuLFBZB3RkruSz5U2R16c5tGvQEzEW4mSShu7B0+QN63PM3kWfyrtizer6mZfaUiYVp77U4QwDbwupiY+QDCClXQMSdk0AnDgbxxwXBTHq5BqDP95Qg+fju51tJt9UetyOOKqKY/uZI6zQIjZ+uLVG4LcjXowrDvPOsNNQhruTa6FeTTylTvAD+q8k1kA3e83H7azXcW6uZpo8mqqPGrN0hJtifE2o4bdzEpVqLUve3YhfHjA1qpBZ/mMY1jEz1vudXY2KBJhtRKYps8Wb4HOholth+V8ouc4+1VwuqV6tlOX5KalrNq442sJPv/VGngK3qOxI8m0Bp4JYiA4sn34dcy+xEJwAGrmygYmYMkhAQwcu7MpVdWpD1w8YO21i2OGGvqdRjKT9r34vgiTj6zRX+126uqRx/yc=
  - secure: FosoggC+ifnWxH/kiB2NVdknBGrqzMCtnikdzATbEVx/um1i2egW0/JAvh6m84JHYuf63R4OO92Et7by4mRoImL8/0ocTGlxSFRzklUCyxH62iPagkfkJUnDSv8gNycWdSOTWwixKKLfDBMGGO7MFTCYDv22HwvrOVXXDRrmV1GAoXFYWpc0o1+3sOxW5Tjo4byaRX6Zzd7B4+v8pfXlpRhCdRj+TFKEgR2niUAeQo53amh9YuH27XebEAR2I5joM3A85bQaRPL8ZHSm2y39PA0cZEmxxQpSJi8e+2/wTEBw2MZdXGDrH7fp8yyAyahos9VCp9RZ0KP/5K1acWyNHgxPJgHDCmBOrPsczOhSvNstoKUw+ck3Ldk/+VQZXsYbCKOEpXHoTqmdq2/Nlu3NPMnJAjbM9UBc0IGQBLEwi6gej5HG6W7NnU7NINBtx69dmzK/VbUUahOhJv+km33QOo8Ko5Ia7q2Dm31RiOp4b9ta7cT4i7qdXb4XznRBl6+U1bW1SiRZOizxyCG594/POu4iN4xnyIeUKRzLFo/RmtA3mOefycLmYT/1wxOYKsy4h+GXvAKJND8aXcBDT3ds5WAMq6UICY3fbfFAqvr8XKCGlHwN15j0fAiPjiCRmAg5zk5LVgR57+sult4moqDQ/jePT+oIZw4qmpO0JPU01TY=
  - secure: R3sTtYJ4uLE94hGMhTIqKxrJXXmH46rEnC0okCcsvziBnKhco8Ebg3vUp08kHkWKAyGXvFwY9E1sk7SPoG4X7qKguv1LsSfGf6z4lpaF2Nh0VD22CNAAAZHEKn7fiGfIbC+gCq7gFLmhoqoVVZQW6gKnfGgjGceHsSikg0ERV/3CcfTk/v+OGYmASWsxN+A+0klOCJTV5+eB9LtrN9RBR3uuPcwiVfGKfTV3EE5tkI4drTdF3XYlJL7FZ1+BF9TFpxj0PBdgkD2zRhGHvWZMm+jwoa+6YgZABT24VDJhADQbM898eejmg5oLei5mgszs5OoxsbhzAPCVpoZhzliFQqX9E5ffL57Wr+s5XA1aSNF+G8004APBKwedCrsDIxS2NQSJtPwvy3siYOSmARQJDsttzgafcKoAMY0PnBN12aLItURdpvu+7Bz46sUwyFA12YAWTqITK5V+d6eYndEHyIRqu+8xqy7AFb2ERsUYus3ixWfWOreCOwZqpRSi/c7I3jL+IzhN6h/KK+DokWQfS/N3phmKLZw0E0n5b7ki5W2WhidADPD2N38GgZ/SvxUjuGgYgbybBRarjUxwHu6KSLkjE21nKsSf2TzEZKvyQ7pQhsCjOir6yuvyrduYI4RXOl1ENwTCMJhkISsWr8/FIqv09YcvaR8KEz6d+yvUiis=
